### ISSUE TITLE
Please indicate it's a subscription service BEFORE installation

### ISSUE THREAD

**Issue by coreyog** [MikeDaniel18/oh-heck-cli#2]
It's kind of a dick move to spring this information so late in the process.

**Comment by Bluscream** [comment]
True, i only found out **after** installing. Maybe it can be forked and rewritten to use a less comprehensive but free API

**Comment by xpurplexamyx** [comment]
Very not cool to not even mention this on the web page, at all.

**Comment by scarletcs** [comment]
"Maybe it's hidden away in the terms of service somewhere, that'd still be pretty bad but at least then it'd be said SOMEWHERE," I thought, before realising it wasn't even a link. (issue #3)

![2022-03-18_19-02-46_firefox](https://user-images.githubusercontent.com/4585677/159068529-dcec99b4-bddb-4c57-9505-5f7b8969d9f5.png)

**Comment by caleb15** [comment]
To be fair it's only $4 a month currently. Anyone wana buy it, try it out, and report back so we can see if it's worth it? 😁

**Comment by MikeDaniel18** [comment]
Thanks for this @coreyog yea, I chucked the website together in three days and that's how it evolved. I'm going to address this issue this week with simpler installation instructions and upfront costs.

**Comment by jacklowrie** [comment]
> True, i only found out **after** installing. Maybe it can be forked and rewritten to use a less comprehensive but free API

Would be nice to see a free tier. This is a cool idea/project, was ready to recommend for people looking to learn the commandline, but $4/month is steep for that, esp for students.

**Comment by MikeDaniel18** [comment]
Now made it clear on the home page that it's a subscription and the cost. It's also been placed above the installation instructions.

<img width="740" alt="image" src="https://user-images.githubusercontent.com/4218450/160419597-9fe62f4b-2648-4027-a1cd-3efd72f77f28.png">

@jacklowrie unfortunately the API costs are huge for this. Longer-term, once we've been able to train the data set more, we should start to see costs going down and speed going up, at which point we can start exploring alternative pricing.

**Comment by Bluscream** [comment]
Maybe demo api keys that allow 20 requests per day or smth like that?
