### ISSUE TITLE
"Terms of Service & Privacy" not specified

### ISSUE THREAD

**Issue by mgiugliano** [MikeDaniel18/oh-heck-cli#3]
There's apparently no working link to the "Terms of Service & Privacy" at the bottom of the home page.

**Comment by scarletcs** [comment]
Confirmed, it's just a `<div>` that has a mouse-hover effect.

![2022-03-18_19-02-46_firefox](https://user-images.githubusercontent.com/4585677/159068334-cc023616-a20e-4b12-acd7-55b40d81c20a.png)

**Comment by MikeDaniel18** [comment]
This has been corrected. Appreciate this. Was a massive oversight on my part. The Privacy Policy explains how and where we store information.
