### ISSUE TITLE
sudo: oh-heck: command not found

### ISSUE THREAD

**Issue by Oyshoboy** [MikeDaniel18/oh-heck-cli#4]
Hey, I'm trying to install everything as mentioned in instructions, but can't authorize with my api key. When I'm entering it, I'm having an error message:
"sudo: oh-heck: command not found"

I'm using it on M1 Silicone machine.

**Comment by MikeDaniel18** [comment]
Hi Helg,

Are you sure you downloaded the ARM build and moved it to the correct location?

Mike

**Comment by Oyshoboy** [comment]
Yes, I've downloaded ARM version and moved it to the /usr/local/bin.

There was no "bin" folder, so I've created new one

**Comment by MikeDaniel18** [comment]
Sorry for the slow reply @Oyshoboy. If there's no bin folder I'm assuming you've never used something like homebrew or other CLI tools that install to /usr/local/bin. You may need to add it to your PATH. You can look at this for some help: https://superuser.com/questions/595818/add-usr-local-sbin-to-the-path-of-a-user - just note that if you're on a new mac you need to add that to `~/.zshrc` and not `~/.bashrc`

**Comment by Oyshoboy** [comment]
Appreciate that! And yes, never used homebrew before.

**Comment by MikeDaniel18** [comment]
Great, closing this issue as it seems to have worked.
