### ISSUE TITLE
Oh-heck command not working after unzipping

### ISSUE THREAD

**Issue by meghanabhange** [MikeDaniel18/oh-heck-cli#5]
Faced this error while installing oh-heck. The command `oh-heck` would yield an error message saying 

`zsh: permission denied: oh-heck`

Turns out, when I ran `sudo unzip ~/Downloads/oh-heck.zip -d /usr/local/bin` it created directory `/usr/local/bin/oh-heck/dist` and `/usr/local/bin/oh-heck/oh-heck`. The commands started working after manually moving `/usr/local/bin/oh-heck/oh-heck` to the directory above. 

Any idea on reasons why this would have happened? :/

**Comment by MikeDaniel18** [comment]
@meghanabhange Sound like one of the distributables isn't compiled correctly. Which one did you download?

**Comment by MikeDaniel18** [comment]
@meghanabhange I found this issue with the Darwin arm64 binary. I've fixed it now and it should work. Thanks for bringing this to my attention. I'll close the issue for now but if it's not fixed from your side, let me know.
